# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-22 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='..apps/'),
        ),
    ]
