# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0002_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='me',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='me', to='signal_app.User'),
            preserve_default=False,
        ),
    ]
