# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=3, max_length=7),
            preserve_default=False,
        ),
    ]
