# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_auto_20171217_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
