# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0004_remove_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='belt_app.User'),
            preserve_default=False,
        ),
    ]
